import type { RadarCandidate } from "@/src/types/opportunity-radar";

export const mockRadarCandidates: RadarCandidate[] = [
  {
    id: "nvda-1",
    ticker: "NVDA",
    companyName: "NVIDIA Corporation",
    category: "unusual_attention",
    headline: "GPU demand signals resurging ahead of next product cycle disclosure",
    thesis:
      "Mock signals indicate unusually elevated research coverage and institutional note volume across data center and AI infrastructure topics. The pattern resembles pre-announcement attention clusters observed in prior cycles.",
    whyNow:
      "Attention metrics spiked in the last 48 hours without a corresponding public news trigger, which historically precedes either a catalyst or a sentiment-driven overshoot.",
    mainCatalyst: "Potential next-gen GPU architecture disclosure or major partner ecosystem announcement",
    bullCase:
      "If demand fundamentals support current attention signals, the stock may be pricing in expectations that have not yet been confirmed publicly. Early positioning before a catalyst could be advantageous for those willing to accept timing risk.",
    bearCase:
      "Attention spikes without clear catalysts frequently resolve as sentiment noise. Current valuation already reflects a significant premium. Disappointment risk is elevated at these levels.",
    nextCheck: "Watch earnings call guidance and partner conference disclosures",
    bullets: [
      "Attention spike in last 48h without a public news trigger",
      "Research note volume well above 30-day average across AI infra topics",
      "First radar appearance — no prior signal history to compare against",
    ],
    attentionScore: 92,
    confidenceScore: 61,
    hypeRiskScore: 74,
    evidenceCount: 18,
    sourceTypes: ["research notes", "technical analysis", "institutional flow"],
    tags: ["AI infrastructure", "data center", "semiconductors", "high conviction"],
    trendStatus: "new_today",
    appearancesLast7Days: 1,
    appearancesLast30Days: 4,
    firstSeenDate: "2026-06-06",
    lastSeenDate: "2026-06-06",
    previousCategories: [],
    isFeatured: true,
    snapshot: { radarConvictionScore: 78, radarSignalStrength: 92, opportunityScore: 82, fundamentalScore: 74, analystUpsidePercent: 18, analystRating: "Outperform", valuationScore: 45, stabilityScore: 62, peRatio: 38.2, week52PositionPercent: 88, marketCapLabel: "~$2.8T", priceChange1WPercent: 3.2 },
  },
  {
    id: "smci-1",
    ticker: "SMCI",
    companyName: "Super Micro Computer",
    category: "beaten_down",
    headline: "Sharp multi-week decline may have overshot fundamental support levels",
    thesis:
      "Stock is down significantly from recent highs amid ongoing uncertainty. Mock signals suggest the selloff may have extended beyond what fundamentals alone justify, creating a potential overreaction setup worth monitoring.",
    whyNow:
      "Price action in the last five sessions shows deceleration in selling pressure with declining volume — a pattern sometimes observed before stabilization.",
    mainCatalyst: "Resolution of filing timeline concerns and updated revenue guidance clarity",
    bullCase:
      "If regulatory and filing concerns resolve favorably, the stock could re-rate meaningfully from current depressed levels. Server demand fundamentals remain supportive of the underlying business.",
    bearCase:
      "Uncertainty around filing and regulatory status has not fully cleared. Another negative development could extend the drawdown significantly from current levels.",
    nextCheck: "Watch for filing updates and regulatory communication in next 30 days",
    bullets: [
      "Selling pressure decelerating after multi-week drawdown",
      "Server demand fundamentals remain intact beneath the regulatory noise",
      "Back on radar after gap — signal renewed this week",
    ],
    attentionScore: 78,
    confidenceScore: 44,
    hypeRiskScore: 68,
    evidenceCount: 14,
    sourceTypes: ["regulatory filings", "price action", "fundamental analysis"],
    tags: ["servers", "AI hardware", "risk event", "beaten down"],
    trendStatus: "back_on_radar",
    appearancesLast7Days: 2,
    appearancesLast30Days: 7,
    firstSeenDate: "2026-05-12",
    lastSeenDate: "2026-06-06",
    previousCategories: ["speculative_upside", "beaten_down"],
    isFeatured: true,
    snapshot: { radarConvictionScore: 64, radarSignalStrength: 88, opportunityScore: 61, fundamentalScore: 52, analystUpsidePercent: 34, analystRating: "Hold", valuationScore: 68, stabilityScore: 28, peRatio: 15.4, week52PositionPercent: 31, marketCapLabel: "~$18B", priceChange1WPercent: -12.4 },
  },
  {
    id: "meta-1",
    ticker: "META",
    companyName: "Meta Platforms",
    category: "possibly_undervalued",
    headline: "Forward multiples appear compressed relative to AI infrastructure investment scale",
    thesis:
      "At current price levels, forward earnings multiples look more conservative than peers investing at a similar or smaller scale in AI infrastructure. The valuation gap may reflect market skepticism around monetization timing rather than fundamental deterioration.",
    whyNow:
      "A recent quarter showed stronger-than-expected engagement metrics, yet the stock has not re-rated to reflect this. The signal suggests a potential valuation lag relative to fundamentals.",
    mainCatalyst: "AI-powered advertising tools beginning to show measurable ROI improvements for advertisers",
    bullCase:
      "If AI monetization tracks ahead of current consensus estimates, the stock could re-rate meaningfully from current multiples over the next two to three quarters.",
    bearCase:
      "CapEx intensity is rising faster than revenue. If AI investments take longer to monetize than expected, multiple compression could persist or deepen.",
    nextCheck: "Watch ad revenue per user and Reels monetization metrics at next earnings",
    bullets: [
      "Forward multiples below AI-infrastructure peer group despite similar scale",
      "Engagement metrics ahead of revised estimates — market hasn't re-rated",
      "Appeared 4× in last 7 days — sustained signal, not a one-off",
    ],
    attentionScore: 63,
    confidenceScore: 71,
    hypeRiskScore: 38,
    evidenceCount: 11,
    sourceTypes: ["fundamental analysis", "earnings transcripts", "valuation models"],
    tags: ["social media", "AI monetization", "advertising", "value"],
    trendStatus: "repeated",
    appearancesLast7Days: 4,
    appearancesLast30Days: 12,
    firstSeenDate: "2026-05-01",
    lastSeenDate: "2026-06-06",
    previousCategories: ["possibly_undervalued"],
    snapshot: { radarConvictionScore: 72, radarSignalStrength: 78, opportunityScore: 78, fundamentalScore: 81, analystUpsidePercent: 22, analystRating: "Outperform", valuationScore: 72, stabilityScore: 74, peRatio: 24.1, week52PositionPercent: 72, marketCapLabel: "~$1.5T", priceChange1WPercent: 1.8 },
  },
  {
    id: "pltr-1",
    ticker: "PLTR",
    companyName: "Palantir Technologies",
    category: "emerging_theme",
    headline: "Defense AI contract pipeline drawing renewed institutional attention",
    thesis:
      "The defense AI procurement cycle appears to be accelerating based on mock signals from government procurement channels and industry conference commentary. Palantir's positioning in this pipeline may be underappreciated at current institutional ownership levels.",
    whyNow:
      "Multiple defense-adjacent catalysts are converging in Q3. The timing aligns with the company's contract renewal cycle and a policy environment supportive of AI infrastructure investment.",
    mainCatalyst: "Expanded government AI platform contract announcements from a major agency",
    bullCase:
      "A material multi-year government AI contract win could significantly expand the revenue base and justify a higher long-term multiple than current consensus assumes.",
    bearCase:
      "Defense procurement timelines are notoriously unpredictable. Commercial segment growth has slowed and may partially offset government tailwinds in the near term.",
    nextCheck: "Monitor government contract announcements and quarterly commercial ARR disclosures",
    bullets: [
      "Defense AI procurement signals accelerating across Q3 catalysts",
      "Institutional ownership may be underweight relative to pipeline opportunity",
      "First appearance — theme is emerging, not yet consensus",
    ],
    attentionScore: 71,
    confidenceScore: 55,
    hypeRiskScore: 58,
    evidenceCount: 9,
    sourceTypes: ["government procurement signals", "institutional flows", "conference notes"],
    tags: ["defense AI", "government contracts", "data analytics", "emerging"],
    trendStatus: "new_today",
    appearancesLast7Days: 1,
    appearancesLast30Days: 3,
    firstSeenDate: "2026-06-06",
    lastSeenDate: "2026-06-06",
    previousCategories: [],
    snapshot: { radarConvictionScore: 71, radarSignalStrength: 71, opportunityScore: 64, fundamentalScore: 48, analystUpsidePercent: 12, analystRating: "Hold", valuationScore: 29, stabilityScore: 55, peRatio: 88.6, week52PositionPercent: 79, marketCapLabel: "~$68B", priceChange1WPercent: 2.5 },
  },
  {
    id: "aapl-1",
    ticker: "AAPL",
    companyName: "Apple Inc.",
    category: "pre_breakout",
    headline: "Price action tightening near multi-month consolidation zone — direction uncertain",
    thesis:
      "The stock has been in a defined range for several months. Mock technical signals indicate a volatility compression setup that often precedes a directional move. The direction of any resolution is uncertain and requires independent validation.",
    whyNow:
      "Volume has declined while price has stabilized — a pattern consistent with accumulation or distribution phases before a range resolution. A developer event is approaching.",
    mainCatalyst: "Upcoming AI-integrated product announcement and developer conference reception",
    bullCase:
      "A meaningful AI product reveal could break the consolidation range to the upside, drawing momentum buyers and expanding the multiple toward consumer AI peers.",
    bearCase:
      "If the product reveal disappoints expectations or macro conditions deteriorate, the range break could resolve to the downside with limited technical support below.",
    nextCheck: "Watch developer conference announcements and early analyst reception",
    bullets: [
      "Volatility compression after 3-month range — classic pre-move pattern",
      "Volume declining while price holds — accumulation or distribution pending",
      "Signal cooling — appeared 3× this week, down from prior pace",
    ],
    attentionScore: 55,
    confidenceScore: 48,
    hypeRiskScore: 42,
    evidenceCount: 8,
    sourceTypes: ["technical analysis", "options flow", "product research"],
    tags: ["consumer tech", "AI products", "consolidation", "watch"],
    trendStatus: "cooling_down",
    appearancesLast7Days: 3,
    appearancesLast30Days: 9,
    firstSeenDate: "2026-05-20",
    lastSeenDate: "2026-06-05",
    previousCategories: ["pre_breakout"],
    snapshot: { radarConvictionScore: 68, radarSignalStrength: 62, opportunityScore: 53, fundamentalScore: 86, analystUpsidePercent: 14, analystRating: "Outperform", valuationScore: 58, stabilityScore: 88, peRatio: 28.3, week52PositionPercent: 54, marketCapLabel: "~$3.3T", priceChange1WPercent: -2.1 },
  },
  {
    id: "tsla-1",
    ticker: "TSLA",
    companyName: "Tesla, Inc.",
    category: "speculative_upside",
    headline: "Catalyst uncertainty high — autonomous timeline speculation elevated",
    thesis:
      "Mock signals show elevated attention metrics driven by autonomous vehicle timeline speculation. The attention is significant but heavily narrative-driven with limited near-term fundamental support for the implied valuation.",
    whyNow:
      "A recent series of autonomous driving demonstration events has elevated speculative interest without corresponding regulatory or delivery milestones.",
    mainCatalyst: "Regulatory approval milestone for commercial autonomous operation in a major jurisdiction",
    bullCase:
      "If a regulatory milestone arrives ahead of market expectations, the re-rating potential is significant given current narrative momentum and existing attention signals.",
    bearCase:
      "Hype risk is among the highest in this radar cycle. The autonomous timeline has been delayed repeatedly. Fundamental valuation at current levels requires near-perfect execution.",
    nextCheck: "Watch regulatory agency communications and autonomous fleet deployment news",
    bullets: [
      "Autonomous demo events spiking speculative attention — no milestone yet",
      "Hype risk at 91 — confidence signal very low at 31",
      "First appearance — narrative-driven, not fundamental-driven",
    ],
    attentionScore: 88,
    confidenceScore: 31,
    hypeRiskScore: 91,
    evidenceCount: 7,
    sourceTypes: ["social signals", "options activity", "news volume"],
    tags: ["EV", "autonomous driving", "high risk", "speculative", "hype elevated"],
    trendStatus: "new_today",
    appearancesLast7Days: 1,
    appearancesLast30Days: 5,
    firstSeenDate: "2026-06-06",
    lastSeenDate: "2026-06-06",
    previousCategories: [],
    snapshot: { radarConvictionScore: 48, radarSignalStrength: 51, opportunityScore: 71, fundamentalScore: 41, analystUpsidePercent: 8, analystRating: "Hold", valuationScore: 21, stabilityScore: 22, peRatio: 124.3, week52PositionPercent: 61, marketCapLabel: "~$580B", priceChange1WPercent: -8.9 },
  },
  {
    id: "amd-1",
    ticker: "AMD",
    companyName: "Advanced Micro Devices",
    category: "unusual_attention",
    headline: "Data center GPU narrative returning attention amid competitive landscape shift",
    thesis:
      "Following a period of relative quiet, mock signals show AMD attention metrics rising again. The pattern may reflect renewed interest in GPU competitive positioning as AI workloads begin diversifying beyond a single accelerator vendor.",
    whyNow:
      "Institutional note volume has increased over the last week without a specific public catalyst, suggesting positioning ahead of an expected product or partnership update.",
    mainCatalyst: "New GPU architecture announcement or a major hyperscaler supply agreement disclosure",
    bullCase:
      "Market share gains in AI inference workloads could materially improve AMD's revenue trajectory above current consensus assumptions.",
    bearCase:
      "The AI accelerator market remains heavily concentrated. AMD faces a significant competitive moat challenge that may take years to close.",
    nextCheck: "Monitor hyperscaler procurement announcements and architecture reveal timing",
    bullets: [
      "Institutional note volume rising without a specific public catalyst",
      "AI workload diversification thesis gaining traction among researchers",
      "Appeared 5× in last 7 days — sustained signal, not a spike",
    ],
    attentionScore: 67,
    confidenceScore: 58,
    hypeRiskScore: 52,
    evidenceCount: 10,
    sourceTypes: ["research notes", "supply chain signals", "institutional flow"],
    tags: ["semiconductors", "AI GPUs", "data center", "competitive dynamics"],
    trendStatus: "repeated",
    appearancesLast7Days: 5,
    appearancesLast30Days: 14,
    firstSeenDate: "2026-04-28",
    lastSeenDate: "2026-06-06",
    previousCategories: ["unusual_attention"],
    snapshot: { radarConvictionScore: 62, radarSignalStrength: 69, opportunityScore: 69, fundamentalScore: 68, analystUpsidePercent: 28, analystRating: "Outperform", valuationScore: 54, stabilityScore: 61, peRatio: 44.7, week52PositionPercent: 55, marketCapLabel: "~$180B", priceChange1WPercent: 4.6 },
  },
  {
    id: "snow-1",
    ticker: "SNOW",
    companyName: "Snowflake Inc.",
    category: "beaten_down",
    headline: "Post-guidance selloff may reflect sentiment overshoot beyond underlying fundamentals",
    thesis:
      "Following a revenue guidance revision, the stock sold off sharply. Mock signals suggest the reaction may have been amplified by position unwinding rather than a fundamental reassessment of the long-term cloud data platform thesis.",
    whyNow:
      "The selling appears to be decelerating after a significant drawdown. If core consumption metrics prove stable, the current setup may represent a monitoring opportunity.",
    mainCatalyst: "Stable or improving net revenue retention in the next quarterly report",
    bullCase:
      "If NRR stabilizes and consumption growth recovers, the stock may revert toward pre-revision levels over the following two to three quarters.",
    bearCase:
      "If consumption softness persists or competitive pressure from cloud-native alternatives accelerates, current levels may not represent the bottom.",
    nextCheck: "Track quarterly NRR figures and customers above the $1M ARR threshold",
    bullets: [
      "Sell-side reaction to guidance may have overshot the fundamental case",
      "NRR stabilization is the key signal — watch next quarter closely",
      "Signal cooling — attention declining from the post-earnings spike",
    ],
    attentionScore: 58,
    confidenceScore: 42,
    hypeRiskScore: 35,
    evidenceCount: 6,
    sourceTypes: ["earnings analysis", "customer survey data", "price action"],
    tags: ["cloud data", "enterprise software", "growth slowdown", "beaten down"],
    trendStatus: "cooling_down",
    appearancesLast7Days: 2,
    appearancesLast30Days: 6,
    firstSeenDate: "2026-05-15",
    lastSeenDate: "2026-06-04",
    previousCategories: ["beaten_down"],
    snapshot: { radarConvictionScore: 73, radarSignalStrength: 76, opportunityScore: 58, fundamentalScore: 44, analystUpsidePercent: 31, analystRating: "Hold", valuationScore: 62, stabilityScore: 47, peRatio: null, week52PositionPercent: 28, marketCapLabel: "~$38B", priceChange1WPercent: -5.3 },
  },
  {
    id: "msft-1",
    ticker: "MSFT",
    companyName: "Microsoft Corporation",
    category: "possibly_undervalued",
    headline: "Cloud growth trajectory versus current multiple may reflect an emerging valuation gap",
    thesis:
      "Azure growth acceleration combined with Copilot monetization progress appears to be outpacing current consensus estimates. The current multiple may be lagging an updated earnings trajectory that models have not yet fully incorporated.",
    whyNow:
      "Enterprise AI adoption signals show an inflection in Copilot seat expansion among mid-market customers — a cohort not yet well-represented in sell-side consensus models.",
    mainCatalyst: "Copilot monetization data showing accelerating per-seat revenue contribution at scale",
    bullCase:
      "If Copilot attach rates continue improving, the earnings power argument strengthens materially at current multiples, potentially supporting a meaningful re-rating.",
    bearCase:
      "The market may already be pricing in successful AI monetization. Any slowdown in adoption would remove the key re-rating catalyst.",
    nextCheck: "Watch cloud segment growth and any Copilot seat count disclosures",
    bullets: [
      "Copilot mid-market expansion not yet in sell-side consensus models",
      "Multiple lagging updated earnings trajectory based on enterprise signals",
      "Back on radar after gap — fundamental case strengthening",
    ],
    attentionScore: 59,
    confidenceScore: 67,
    hypeRiskScore: 29,
    evidenceCount: 13,
    sourceTypes: ["enterprise survey data", "earnings models", "fundamental analysis"],
    tags: ["enterprise software", "cloud", "AI monetization", "blue chip"],
    trendStatus: "back_on_radar",
    appearancesLast7Days: 2,
    appearancesLast30Days: 8,
    firstSeenDate: "2026-05-08",
    lastSeenDate: "2026-06-06",
    previousCategories: ["possibly_undervalued"],
    snapshot: { radarConvictionScore: 71, radarSignalStrength: 73, opportunityScore: 76, fundamentalScore: 89, analystUpsidePercent: 17, analystRating: "Outperform", valuationScore: 61, stabilityScore: 91, peRatio: 32.5, week52PositionPercent: 68, marketCapLabel: "~$3.0T", priceChange1WPercent: 0.8 },
  },
  {
    id: "rivn-1",
    ticker: "RIVN",
    companyName: "Rivian Automotive",
    category: "emerging_theme",
    headline: "Fleet contract discussions and delivery ramp returning focus to EV challenger",
    thesis:
      "New mock signals suggest renewed institutional interest tied to a potential large commercial fleet partnership announcement. The EV challenger thesis has been beaten down significantly, which may make the risk/reward more interesting if delivery and partnership milestones land.",
    whyNow:
      "Multiple fleet operators are reported to be in re-evaluation mode after initial EV deployments showed better-than-expected total cost of ownership metrics in controlled environments.",
    mainCatalyst: "New commercial fleet contract announcement or a positive delivery ramp update",
    bullCase:
      "A significant fleet deal win could demonstrate commercial viability and provide a cash flow path that current models do not adequately reflect.",
    bearCase:
      "The EV sector remains under macro pressure. Cash burn is significant and any delay in fleet contracts extends runway concerns materially.",
    nextCheck: "Monitor fleet partnership announcements and quarterly delivery reports",
    bullets: [
      "Fleet operators re-evaluating after better-than-expected EV TCO results",
      "Commercial fleet theme building — appeared 3× in last 7 days",
      "Risk elevated but risk/reward may be improving at current levels",
    ],
    attentionScore: 61,
    confidenceScore: 38,
    hypeRiskScore: 62,
    evidenceCount: 5,
    sourceTypes: ["fleet operator signals", "delivery tracking", "sector analysis"],
    tags: ["EV", "commercial fleet", "emerging", "high risk"],
    trendStatus: "repeated",
    appearancesLast7Days: 3,
    appearancesLast30Days: 10,
    firstSeenDate: "2026-05-03",
    lastSeenDate: "2026-06-06",
    previousCategories: ["emerging_theme"],
    snapshot: { radarConvictionScore: 62, radarSignalStrength: 64, opportunityScore: 52, fundamentalScore: 28, analystUpsidePercent: 42, analystRating: "Hold", valuationScore: 44, stabilityScore: 18, peRatio: null, week52PositionPercent: 22, marketCapLabel: "~$14B", priceChange1WPercent: -6.7 },
  },
  {
    id: "sofi-1",
    ticker: "SOFI",
    companyName: "SoFi Technologies",
    category: "pre_breakout",
    headline: "Fintech positioning ahead of rate cycle shift may support a technical setup",
    thesis:
      "Mock signals indicate the stock is forming a pattern consistent with pre-breakout consolidation, supported by improving fundamentals in student loan refinancing and bank deposit growth as rate expectations begin shifting.",
    whyNow:
      "Rate cut expectations are being repriced across markets, which historically benefits fintech lenders with variable-rate lending books and refinancing origination pipelines.",
    mainCatalyst: "Federal Reserve guidance shift and subsequent acceleration in refinancing origination volume",
    bullCase:
      "If the rate environment turns more favorable within the expected timeframe, refinancing origination volumes could accelerate meaningfully, supporting earnings above current estimates.",
    bearCase:
      "Rate timelines remain highly uncertain. If higher-for-longer persists, the fundamental tailwind thesis may not materialize in the modeled timeframe.",
    nextCheck: "Watch Fed communication, origination data, and member growth metrics",
    bullets: [
      "Rate cut expectations being repriced — directly benefits lending book",
      "Technical consolidation pattern consistent with pre-directional setup",
      "First appearance — worth monitoring for confirmation signals",
    ],
    attentionScore: 52,
    confidenceScore: 46,
    hypeRiskScore: 44,
    evidenceCount: 7,
    sourceTypes: ["macro signals", "technical analysis", "earnings models"],
    tags: ["fintech", "student loans", "rate sensitive", "watch"],
    trendStatus: "new_today",
    appearancesLast7Days: 1,
    appearancesLast30Days: 2,
    firstSeenDate: "2026-06-06",
    lastSeenDate: "2026-06-06",
    previousCategories: [],
    snapshot: { radarConvictionScore: 55, radarSignalStrength: 58, opportunityScore: 55, fundamentalScore: 39, analystUpsidePercent: 38, analystRating: "Hold", valuationScore: 57, stabilityScore: 43, peRatio: 41.2, week52PositionPercent: 43, marketCapLabel: "~$12B", priceChange1WPercent: 3.4 },
  },
  {
    id: "ionq-1",
    ticker: "IONQ",
    companyName: "IonQ Inc.",
    category: "speculative_upside",
    headline: "Quantum computing theme cycling — speculative attention fading from recent peak",
    thesis:
      "The quantum computing narrative drove significant attention earlier in the cycle. Mock signals now show cooling attention metrics, though the stock remains in the speculative tier with meaningful upside optionality if commercial milestones arrive ahead of the current timeline.",
    whyNow:
      "The recent pullback from narrative-driven highs may represent a more rational entry point for highly speculative positions — if the commercial timeline thesis is accepted at face value.",
    mainCatalyst: "Demonstrated commercial quantum advantage in a specific, verifiable industrial application",
    bullCase:
      "If quantum advantage is demonstrated commercially before peers, the narrative could reignite and drive a significant re-rating from current depressed attention levels.",
    bearCase:
      "Commercial quantum timelines remain speculative and have repeatedly extended beyond prior estimates. Fundamentals do not yet support current valuations without the narrative premium.",
    nextCheck: "Monitor milestone announcements and any commercial contract disclosures",
    bullets: [
      "Quantum narrative attention fading from its peak — signal cooling",
      "Hype risk at 82 — pullback may reflect speculative unwinding",
      "Appeared 2× this week — still active but losing momentum",
    ],
    attentionScore: 44,
    confidenceScore: 27,
    hypeRiskScore: 82,
    evidenceCount: 4,
    sourceTypes: ["research publications", "conference commentary", "price action"],
    tags: ["quantum computing", "deep speculative", "narrative", "cooling"],
    trendStatus: "cooling_down",
    appearancesLast7Days: 2,
    appearancesLast30Days: 11,
    firstSeenDate: "2026-04-15",
    lastSeenDate: "2026-06-04",
    previousCategories: ["speculative_upside", "emerging_theme"],
    snapshot: { radarConvictionScore: 42, radarSignalStrength: 45, opportunityScore: 43, fundamentalScore: 18, analystUpsidePercent: 26, analystRating: "Hold", valuationScore: 16, stabilityScore: 28, peRatio: null, week52PositionPercent: 38, marketCapLabel: "~$4.5B", priceChange1WPercent: -14.2 },
  },
];
